### ISSUE TITLE
Gives error "Only absolute URLs are supported" even though the URL is absolute

### ISSUE THREAD

**Issue by LukasDoesDev** [node-fetch/node-fetch#1015]
I did
```js
require('node-fetch')('http://localhost:3000/')
```
and it gave me an error: TypeError: Only absolute URLs are supported

**Reproduction**

1. Get node version 15.2.1
2. run `npm install node-fetch@2.6.1`
3. run `node -p "require('node-fetch')('http://localhost:3000/')"`

**Expected behavior**

I expected it to run fine without any errors and return the response.
https://www.npmjs.com/package/node-fetch#fetchurl-options

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |2.6.1
| node             |15.2.1
| npm              |6.14.8
| Operating System |Windows 10 v2004 build 19041.630

**Additional context**

**Comment by tekwiz** [comment]
@LukasDoesDev I'm not able to replicate this with node-fetch 2.6.1 and node 15.2.1 on a mac.  Could your issue with the command line or PowerShell?  If you drop that line into a .js file and run it with node, does the same thing happen?  If you open node interactively (`node -i`) and paste that line, does it run?

```
$ node -p "require('./dist/index.cjs')('http://localhost:3000/').then(console.dir, console.dir)"
Promise { <pending> }
Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://localhost:3000/',
    status: 200,
    statusText: 'OK',
    headers: Headers { [Symbol(query)]: [Array], [Symbol(context)]: null },
    counter: 0,
    highWaterMark: 16384
  }
}
```

**Comment by LukasDoesDev** [comment]
> If you drop that line into a .js file and run it with node, does the same thing happen?

Still gives the error.

> If you open node interactively (node -i) and paste that line, does it run?

Still gives the error.

I'll add the error here as I didn't seem to add it in the original post.

```
➜  Test node .\test.js
D:\CodingProjects\Discord\Bord\node_modules\node-fetch\lib\index.js:1305
                throw new TypeError('Only absolute URLs are supported');
                      ^

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (D:\CodingProjects\Discord\Bord\node_modules\node-fetch\lib\index.js:1305:9)
    at D:\CodingProjects\Discord\Bord\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (D:\CodingProjects\Discord\Bord\node_modules\node-fetch\lib\index.js:1407:9)
    at ClientRequest.<anonymous> (D:\CodingProjects\Discord\Bord\node_modules\node-fetch\lib\index.js:1539:15)
    at ClientRequest.emit (node:events:329:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:652:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
    at Socket.socketOnData (node:_http_client:518:22)
    at Socket.emit (node:events:329:20)
```

**Comment by tekwiz** [comment]
@LukasDoesDev Can you post your package.json and test.js files? Based on a separate conversation, I'm thinking this is related to something within the discord library.

**Comment by itzTheMeow** [comment]
im having the same issue with the URL "https://discord.com/api/v8/oauth2/token"
Package:
```{
  "name": "token-app",
  "version": "0.0.1",
  "description": "A token app.",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.17.1",
    "node-fetch": "^2.6.1"
  }
}
```
And server.js:
```
const express = require("express");
const fetch = require("node-fetch");
const app = express();

app.get("/", (req, res) => {
  fetch("https://discord.com/api/v8/oauth2/token", {
    method: "POST",
    body: "grant_type=client_credentials&scope=identify",
    headers: {
      Authorization:
        "Basic [redacted]",
      "Content-Type": "application/x-www-form-urlencoded"
    }
  })
    .then(r => r.json())
    .then(response => {
      res.json(response);
    });
});

app.use(express.static("site"));

const listener = app.listen(process.env.PORT, () => {
  console.log("Your app is listening on port " + listener.address().port);
});
```

**Comment by mathiasschuetz** [comment]
Hello I got the same problem. 

I have only node-fetch as a dependency.
`const headers = new Headers();
        headers.append("Accept", "application/x.dx4.publicws.rest+json;version=4.0.1");
        headers.append("Content-Type", "application/json");
        headers.append("Authorization", "Bearer " + global.db.rwt);

        const request = {
            "customerName": global.db.customerName,
            "userName": global.db.username,
            "password": global.db.password
        };

        const url = new URL("/restws/publicws/rest/api/v1/login", global.db.url);
        console.log(url);

        const response = await fetch({
            mode: "cors",
            method: "POST",
            url: url.href,
            headers: headers,
            body: JSON.stringify(request)
        });`

URL: 'https://********/restws/publicws/rest/api/v1/login'
Node Version 14.15.4

**Comment by tekwiz** [comment]
@mathiasschuetz Can you please post 1) your full script, 2) the result of `console.dir(global.db)`, and 3) the version of node-fetch you are using?

**Comment by mathiasschuetz** [comment]
Hello @tekwiz 

1. 


    async function login() {
        const headers = new Headers();
        headers.append("Accept", "application/x.dx4.publicws.rest+json;version=4.0.1");
        headers.append("Content-Type", "application/json");
        headers.append("Authorization", "Bearer " + global.db.rwt);

        const request = {
            "customerName": global.db.customerName,
            "userName": global.db.username,
            "password": global.db.password
        };

        const url = new URL("/restws/publicws/rest/api/v1/login", global.db.url);
        console.log(url);

        const response = await fetch({
            mode: "cors",
            method: "POST",
            url: url,
            headers: headers,
            body: JSON.stringify(request)
        });

        if (response.ok) {
            return await response.text();
        } else {
            return undefined;
        }
    }


2) no sorry it has only user information
3) node-fetch: 2.6.1

**Comment by tekwiz** [comment]
> 2) no sorry it has only user information

@mathiasschuetz That's reasonable, but I at least need to see the output of `console.dir(global.db.url)`

**Comment by tbrannam** [comment]
I have had a similar issue, and the problem was multiple versions of node-fetch.  In my case I was running in a monorepo and the test app and the support packages resolved to different node_modules folder.   Somewhere deep in the implementation there is a check against a JS symbol which would not match in this case.

**Comment by mathiasschuetz** [comment]
@tbrannam yes you are right. I got fixed my problem by using [FormData](https://www.npmjs.com/package/form-data) and [Axios](https://www.npmjs.com/package/axios) in combination

**Comment by LukasDoesDev** [comment]
I can't give the package.json because i lost the whole project to a drive failure. Good thing most of my projects are on GitHub or GitLab.

**Comment by LukasDoesDev** [comment]
package.json: https://www.github.com/LukasDoesDev/bord/tree/master/package.json

**Comment by OZZlE** [comment]
> I have had a similar issue, and the problem was multiple versions of node-fetch. In my case I was running in a monorepo and the test app and the support packages resolved to different node_modules folder. Somewhere deep in the implementation there is a check against a JS symbol which would not match in this case.

how did you solve that?

**Comment by tbrannam** [comment]
> > I have had a similar issue, and the problem was multiple versions of node-fetch. In my case I was running in a monorepo and the test app and the support packages resolved to different node_modules folder. Somewhere deep in the implementation there is a check against a JS symbol which would not match in this case.
> 
> how did you solve that? @tbrannam

I changed the example project to only reference node-modules as a peer dependency.  And relied on the root node_modules folder to already have it installed.

**Comment by steelx** [comment]
same here windows 10

**Comment by LinusU** [comment]
@pavelloz @steelx could you submit the exact code that aren't working, along with exact versions of node-fetch, node, npm, and os?

```sh
node -p "require('./dist/index.cjs')('http://localhost:3000/').then(console.dir, console.dir)"
```

Is this not working?
