### ISSUE TITLE
Encoding error not caught

### ISSUE THREAD

**Issue by iAlex97** [node-fetch/node-fetch#1114]
I am using this module to crawl various webpages with unkown encodings. I use the `convertedText()` method. Relevant piece of code:

```typescript
return fetch(url, { timeout: this.timeoutMs(), agent: agent })
            .then((res) => {
                logger.silly(`[StaticStrategy] [${res.status}] ${url}`);
                return Promise.all([this.mapHeaders(res), res.status, res.textConverted()]);
            })
            .then(([headers, status, html]) => {
                return this.parseDocument(status, url, html, headers, this.charThreshold, this.failOnNoscript);
            })
            .then((doc) => {
                const t1: number = Date.now();
                return {
                    result: {
                        userAgent: this.userAgent,
                        responseHeaders: doc.headers,
                        statusCode: doc.statusCode,
                        scheme: this.scheme,
                        domain: this.domain,
                        url: this.pageUrl,
                        fetchTimeMs: t1 - t0,
                        content: doc.html,
                        urls: this.filterHrefs(doc.urls),
                    }
                } as ICrawlingResult;
            })
            .catch((e: FetchError) => {
                const retry: boolean = !errorCodes.includes(e.errno || '') && e.type !== 'request-timeout';
                return {
                    error: {
                        retry: retry,
                        message: `[StaticStrategy] error ${e.message}`,
                    },
                } as ICrawlingResult;
            });
```

Additionally, I register handlers for `unhandledRejection` and `uncaughtException`:
```typescript
process.once('unhandledRejection', async (reason: {} | null | undefined) => {
        logger.error('worker unhandledRejection', { err: reason });
        process.exit(1);
    });
    process.once('uncaughtException', async (error: Error) => {
        logger.error('worker uncaughtException', { err: error });
        process.exit(2);
    });
``` 

However, I keep seeing uncaught errors:
```

Mar 11, 2021 @ 12:58:56.123 | Error: Encoding not recognized: 'UTF-8,TEXT/HTML' (searched as: 'utf8texthtml')
-- | --
  | Mar 11, 2021 @ 12:58:56.123 | at Object.getCodec (/var/www/soleadify-avro-aggregator/node_modules/encoding/node_modules/iconv-lite/lib/index.js:104:23)
  | Mar 11, 2021 @ 12:58:56.123 | at Object.getDecoder (/var/www/soleadify-avro-aggregator/node_modules/encoding/node_modules/iconv-lite/lib/index.js:125:23)
  | Mar 11, 2021 @ 12:58:56.123 | at Object.decode (/var/www/soleadify-avro-aggregator/node_modules/encoding/node_modules/iconv-lite/lib/index.js:38:25)
  | Mar 11, 2021 @ 12:58:56.123 | at convertIconvLite (/var/www/soleadify-avro-aggregator/node_modules/encoding/lib/encoding.js:59:26)
  | Mar 11, 2021 @ 12:58:56.123 | at convert (/var/www/soleadify-avro-aggregator/node_modules/encoding/lib/encoding.js:35:22)
  | Mar 11, 2021 @ 12:58:56.123 | at convertBody (/var/www/soleadify-avro-aggregator/node_modules/node-fetch/lib/index.js:497:9)
  | Mar 11, 2021 @ 12:58:56.123 | at /var/www/soleadify-avro-aggregator/node_modules/node-fetch/lib/index.js:307:11
  | Mar 11, 2021 @ 12:58:56.123 | at runMicrotasks (<anonymous>)
  | Mar 11, 2021 @ 12:58:56.123 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | Mar 11, 2021 @ 12:58:56.123 | at async Promise.all (index 2)
```

Am I missing something here, how can I properly catch this error and handle it? 

**Reproduction**

1. Visit a page whose encoding is not supported by `iconv-lite`

**Expected behavior**

I think `node-fetch` should throw a `FetchError` specifying that it couldn't decode the body. 

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 12.20.1
| encoding              | 0.1.13

**Additional context**

[http://burlandtm.com/1990-2000-arup-associates.html](http://burlandtm.com/1990-2000-arup-associates.html)

This url will produce:
```
Error: Encoding not recognized: 'NONE' (searched as: 'none')
    at Object.getCodec (/home/Projects/test/node_modules/encoding/node_modules/iconv-lite/lib/index.js:104:23)
    at Object.getDecoder (/home/Projects/test/node_modules/encoding/node_modules/iconv-lite/lib/index.js:125:23)
    at Object.decode (/home/Projects/test/node_modules/encoding/node_modules/iconv-lite/lib/index.js:38:25)
    at convertIconvLite (/home/Projects/test/node_modules/encoding/lib/encoding.js:59:26)
    at convert (/home/Projects/test/node_modules/encoding/lib/encoding.js:35:22)
    at convertBody (/home/Projects/test/node_modules/node-fetch/lib/index.js:497:9)
    at /home/Projects/test/node_modules/node-fetch/lib/index.js:307:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 2)
    at async /home/Projects/test/build/test.read.js:21:21
```

**Comment by iAlex97** [comment]
Upon further inspection, it's just a console log error statement from the `encoding` lib
