### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by govindrai** [node-fetch/node-fetch#1166]
**Reproduction**

Run the following code
```javascript
const fetch = require("node-fetch");

async function getApps() {
    const projectId = "​123456789abcdefgh"; // dummy project id
    const res = await fetch(`https://realm.mongodb.com/api/admin/v3.0/groups/${projectId}/apps`, {
        headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": `Bearer 123.bea.retok23`, // dummy auth token
        },
    });

    if (res.ok) {
        console.log(await res.json());
    } else {
        console.log("REQ failed");
        console.log(res.status);
        console.log(await res.text());
    }
}

getApps();
```

Running this returns: 
```
(node:12205) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at request (https.js:313:10)
    at /Users/govindrai/Projects/beautifulai/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/Users/govindrai/Projects/beautifulai/node_modules/node-fetch/lib/index.js:1407:9)
    at getApps (/Users/govindrai/Projects/beautifulai/realm/deployer.js:54:23)
    at Object.<anonymous> (/Users/govindrai/Projects/beautifulai/realm/deployer.js:71:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Expected behavior**

The url as per this [fix](https://github.com/node-fetch/node-fetch/commit/f3b00aaf8ed847fd3f30b1b7182cdafa411d02f0) should be escaped automatically.

If I remove the `const projectId = "​123456789abcdefgh"; // dummy project id` line from the above sample and insert the projectId string directly into the url without template strings like `const res = await fetch("https://realm.mongodb.com/api/admin/v3.0/groups/123456789abcdefgh/apps", {
` the request goes through (but the request fails with a 401 of course since the api key and token are dummy values). 

Example without template string interpolation:

```javascript
const fetch = require("node-fetch");

async function getApps() {
    const res = await fetch("https://realm.mongodb.com/api/admin/v3.0/groups/123456789abcdefgh/apps", {
        headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": `Bearer 123.bea.retok23`,
        },
    });

    if (res.ok) {
        console.log(await res.json());
        console.log(await res.text());
    } else {
        console.log("REQ failed");
        console.log(res.status);
        console.log(await res.text());
    }
}

getApps();
```

Running this returns:
```
REQ failed
401
{"error":"invalid character '×' looking for beginning of value"}
```

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14.16.0
| npm              |  7.7.5
| Operating System | MacOS Big Sur 11.2.3

**Comment by StefanV85** [comment]
+1   i have also the same problem that an url is not automatically encoded.

**Comment by jimmywarting** [comment]
would this work?

```js
new URL(`https://realm.mongodb.com/api/admin/v3.0/groups/${projectId}/apps`).toString()
```

cuz we are using URL to parse the url now in v3
