### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'signal' in /api/auth/stats/857656800173621308

### ISSUE THREAD

**Issue by ddzin-dev** [node-fetch/node-fetch#1196]
> Code:
```
const fetch = require("node-fetch");

module.exports = async client => {
  console.log(`Servers [${client.guilds.cache.size}] Users [${client.users.cache.size}]`);


  client.user.setActivity('Cachorrão do ddzin :)', {type: 'PLAYING'});
  console.log('online');

  
var requestOptions = {
  method: 'POST',
  headers: {
    "authorization": "my-token-censoured",
    "Content-Type": "json"
  },
  body: JSON.stringify({"server_count": client.guilds.cache.size})
};

fetch(`bot.sunlabs.gq`, `/api/auth/stats/857656800173621308`)
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);

}
```

> Console:
```
TypeError: Cannot use 'in' operator to search for 'signal' in /api/auth/stats/857656800173621308
    at new Request (/home/runner/api-bot/node_modules/node-fetch/lib/index.js:1219:16)
    at /home/runner/api-bot/node_modules/node-fetch/lib/index.js:1409:19
    at new Promise (<anonymous>)
    at fetch (/home/runner/api-bot/node_modules/node-fetch/lib/index.js:1407:9)
    at module.exports (/home/runner/api-bot/events/ready.js:20:1)
    at Client.emit (events.js:314:20)
    at WebSocketManager.triggerClientReady (/home/runner/api-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/runner/api-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/home/runner/api-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
```

**Comment by tudorgalt** [comment]
I guess you already found the culprit, but because I saw this among the first results in google for this error, I think an answer is good:
The issue is that instead of using the `requestOptions` object as the second param to the fetch call, you used a string.

The solution is to give an object as the second parameter. So something like this would work:
```

fetch(`bot.sunlabs.gq/api/auth/stats/857656800173621308`, requestOptions)
  .then(response => response.text())
  .then(console.log)
  .catch(console.error);
  ```
