### ISSUE TITLE
V3 breaks webpack and jest 

### ISSUE THREAD

**Issue by heath-freenome** [node-fetch/node-fetch#1265]
Please document how to get things working with jest and webpack like formatJS does for react-intl: https://formatjs.io/docs/react-intl#jest

Right now my webpack blows up with:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <path>/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of <path>/node_modules/node-fetch/src/index.js from <path>/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <path>/node_modules/node-fetch/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.node-fetch (<path>/external "node-fetch":1:1)
    at __webpack_require__ (<path>/build/webpack:/app/webpack/bootstrap:24:1)
    at fn (<path>/build/webpack:/app/webpack/runtime/hot module replacement:61:1)
    at Module../src/server/createNodeWretch.js (<path>/build/server.js:7943:68)
    at __webpack_require__ (<path>/build/webpack:/app/webpack/bootstrap:24:1)
```
and Jest with:
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    <path>/node_modules/node-fetch/src/index.js:9
    import http from 'http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import url from 'url';
      3 | import FormData from 'form-data';
    > 4 | import fetch from 'node-fetch';
        | ^
      5 |
```
**Expected behavior**
I'm using the `import` syntax as described in the migration guide... but the guide is incomplete.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0
| node             | 14.16.0
| npm              | 6.14.11
| Operating System | macOS big sur

**Comment by RedGuy12** [comment]
You can not `require` ESM modules, and this is now an ESM module. Either stick with 2.0 or move to ESM yourself (recommended)

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by heath-freenome** [comment]
> You can not `require` ESM modules, and this is now an ESM module. Either stick with 2.0 or move to ESM yourself (recommended)
> 
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I am NOT requiring... As I said in the bug report, I have always used the `import` syntax... You need to document how to get jest and webpack to transpile your library

**Comment by heath-freenome** [comment]
Hmmm, just for the heck of it I tried something similar to what react-intl suggests and it doesn't work... Maybe something is missing in how `node-fetch` is defined in the `package.json`? or perhaps it is missing the `index.js` file in the main directory like `react-intl` has?

**Comment by loynoir** [comment]
@heath-freenome 

```sh
export NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules"
```

```
// jest.config.js
module.exports = {
  // [...]
  preset: 'ts-jest/presets/default-esm', // or other ESM presets
  globals: {
    'ts-jest': {
      useESM: true,
    },
  },
}
```

**Comment by loynoir** [comment]
@RedGuy12 If you check the source code of jest, you will find out the core problem here is not `require`.
Jest is running under `vm` module, and **Node.js vm module support ESM is  experimental**
> `--experimental-vm-modules`

**Comment by LinusU** [comment]
Documentation for getting this to work with Jest is here:

https://jestjs.io/docs/ecmascript-modules

**Comment by loynoir** [comment]
@LinusU 

Jest
> Note that due to its experimental nature there are **many** bugs and missing features in Jest's implementation, both **known and unknown**. You should check out the tracking issue and the label on the issue tracker for the latest status.

Node.js
> --experimental-vm-modules

We both want ESM world, but reality is ecosystem is not ready yet.

Instead of "just use all the experimental features", which seems like an uncontrolable black box,

Can't we just dual-modulize node-fetch?

**Comment by jimmywarting** [comment]
> Can't we just dual-modulize node-fetch?

this are being discussed here: #1227

**Comment by LinusU** [comment]
> We both want ESM world, but reality is ecosystem is not ready yet.

I'm not sure about that, Jest is just one of many test runners. I don't think that just because its support is experimental, the whole ecosystem isn't ready.

> Can't we just dual-modulize node-fetch?

I think a better approach is to stick with node-fetch 2.x if you are having troubles, see the discussion here: https://github.com/node-fetch/node-fetch/pull/1227

**Comment by loynoir** [comment]
@jimmywarting 
> this are being discussed here
I know. But here is a specific scenario, just jest, not some abstraction.

@LinusU
> I'm not sure about that, Jest is just one of many test runners. I don't think that just because its support is experimental, the whole ecosystem isn't ready.

Node.js mark as `--experimental-vm-modules`, jest official document states **many known and unknown bugs**.
`I don't think` is not very convincing both Node.js and jest official state them as experimental.

- `Just use all the experimental features if you want node-fetch@3`
- `If you don't, just don't update, and stay on node-fetch@2`
Emm, seems very frustrating.

**Comment by LinusU** [comment]
> Node.js mark as `--experimental-vm-modules`, jest official document states **many known and unknown bugs**.
> `I don't think` is not very convincing both Node.js and jest official state them as experimental.

Yes, but I don't think that `vm-modules` isn't often used that much at all? At least I've personally never seen it used outside of Jest...

> * `Just use all the experimental features if you want node-fetch@3`
> * `If you don't, just don't update, and stay on node-fetch@2`
> 
> Emm, seems very frustrating.

Why does this seem frustrating?

**Comment by loynoir** [comment]
> Yes, but I don't think that vm-modules isn't often used that much at all? 
Here is the problem. Please check jest source code.
All jest running under vm.

**Comment by loynoir** [comment]
- `Just use all the experimental features if you want node-fetch@3`
- `If you don't, just don't update, and stay on node-fetch@2`
> Why does this seem frustrating?
Because there is a proper solution for current time point, dual-module.
But I know you against dual-module...

**Comment by LinusU** [comment]
> > Yes, but I don't think that vm-modules isn't often used that much at all?
> 
> Here is the problem. Please check jest source code.
> All jest running under vm.

Yes I know that Jest is using vm-modules. What I meant was that the majority of the ecosystem is not using vm-modules, and thus holding back the entire ecosystem just because Jest does it feels a bit strange to me 🤔 



> > * `Just use all the experimental features if you want node-fetch@3`
> > * `If you don't, just don't update, and stay on node-fetch@2`
> >
> > Why does this seem frustrating?
> 
> Because there is a proper solution for current time point, `dual-module`.
> But I know you against dual-module...

Well, I am personally against dual-module, but that is because there are clear drawbacks with it which is discussed in the larger thread.

I think it's better if we concentrate specifically on Jest and WebPack compatibility (without going away from ESM-only) in this issue. In fact, it might be better to split it up into two issues: one for Jest, and one for WebPack.

I've used ESM-only modules in WebPack before so I'm not entirely sure what the problems are there, but I believe that there are workarounds/fixes available...

**Comment by Thomasan1999** [comment]
I'm using ESM and Rollup in my project but Jest still had the same problem with loading the package. Here's what worked for me:

`jest.config.ts`:
```
export default {
  preset: 'ts-jest/presets/js-with-ts-esm',
  transformIgnorePatterns: [
      'node_modules/(?!(fetch-blob|node-fetch)/)'
  ]
}
```
`tsconfig.json`:
```
{
  "compilerOptions": {             
    "allowJs": true,                       
    "esModuleInterop": true
  }
}
```

Credit goes to: https://stackoverflow.com/a/66480267/8746088

**Comment by heath-freenome** [comment]
@Thomasan1999... That did it for me!!! it was `fetch-blob` that was the savior...

**Comment by heath-freenome** [comment]
@jimmywarting If you replicate the documentation for `react-intl` and for jest use:
```
  transformIgnorePatterns: [
      'node_modules/(?!(fetch-blob|node-fetch)/)'
  ]
```

And for webpack:
```
  include: [
    path.join(__dirname, 'node_modules/fetch-blob'),
    path.join(__dirname, 'node_modules/node-fetch'),
  ]
```
OR
```
exclude: /node_modules\/(?!fetch-blob|node-fetch)/,
```

**Comment by heath-freenome** [comment]
> @Thomasan1999... That did it for me!!! it was `fetch-blob` that was the savior...

False alarm... I forgot to `npm update` with `node-fetch` v3 :(

**Comment by loynoir** [comment]
@heath-freenome Not false alarm. I saw and tested it! 😄
@Thomasan1999 Awesome! As long as `node-fetch` not using hard core ESM, like top level await, now I can get rid of `experimental` flag. 😘

```sh
[tempDir] $ pnpm i -D jest ts-jest ts-node typescript node-fetch && jest && tail -n +1 jest.config.ts tsconfig.json esmDeps.spec.ts

==> jest.config.ts <==
export default {
  preset: 'ts-jest/presets/js-with-ts-esm',
  transformIgnorePatterns: [
      'node_modules/\\.pnpm/(?!node-fetch|fetch-blob)',
  ]
}

==> tsconfig.json <==
{
  "compilerOptions": {             
    "allowJs": true,                       
    "esModuleInterop": true
  }
}

==> esmDeps.spec.ts <==
import nf from 'node-fetch'

describe("esmDeps", () => {
  it("esmDeps", () => {
    console.warn(nf)
  });
});
```

**Comment by heath-freenome** [comment]
> @heath-freenome Not false alarm. I saw and tested it! 😄
@Thomasan1999 Awesome! As long as node-fetch not using hard core ESM, like top level await, now I can get rid of experimental flag. 😘

I'm not using typescript in my project (yet)

**Comment by loynoir** [comment]
Since @Thomasan1999 got a solution without any experimental features! 

I currently have no real-world problem with node-fetch. 😄

FYI @jimmywarting @LinusU, not hard core ESM yet, like top-level await will break this solution.

**Comment by loynoir** [comment]
@heath-freenome 
The core tech here is using `transformer`, exclude **ALL** `ESM-only` package from `transformIgnorePatterns`, which means 
- let transformer convert **ALL** `ESM-only` package to **CJS** on-the-fly of jest

Maybe you need `babel-jest` or `jest-babel` something, let babel convert **ALL** `ESM-only` package to **CJS** on-the-fly of jest.

FYI, `ESM-only` package node-fetch depends on `ESM-only` fetch-blob.
So, you need to at least `node-fetch` and `fetch-blob`, add adjust according to error msg.

Good luck!

**Comment by xbreaker** [comment]
@heath-freenome

For Node JS project that's worked for me, may be you can do the same for webpack:

`jest.config.ts:`
```
export default {
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
  transformIgnorePatterns: [
      'node_modules/(?!(fetch-blob|node-fetch)/)'
  ]
}
```
`babel.config.cjs`
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current'
        }
      }
    ]
  ],
  plugins: ['babel-plugin-transform-es2015-modules-commonjs', 'babel-plugin-transform-import-meta']
}
```

**Comment by ChromeQ** [comment]
Thanks @xbreaker that worked great until node-fetch updated to v3.1.0 now.
The dependencies changed (https://github.com/node-fetch/node-fetch/blob/v3.1.0/package.json#L65) so the transformIgnorePatterns needs updating to include them

```
transformIgnorePatterns: [
    'node_modules/(?!(data-uri-to-buffer|formdata-polyfill|fetch-blob|node-fetch)/)',
]
```

There are other issues with node-fetch@3.1 which causes problems with jest, specifically the usage of node:prefixes. I have added another workaround details here: https://github.com/node-fetch/node-fetch/issues/1367#issuecomment-977473094

Hope this helps somebody
