### ISSUE TITLE
importing fails

### ISSUE THREAD

**Issue by pjalsGit** [node-fetch/node-fetch#1273]
**Reproduction**

1. get latest version of node-fetch (with yarn?)
2. try to import node-fetch (using typescript?)
3. complains about `unexpected identifier` (`import http from 'http';`)

**Expected behavior**

imports the library correctly

**Screenshots**
```
Done in 4.61s.
/home/me/Projects/UAPK/node_modules/node-fetch/src/index.js:9
import http from 'http';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/me/Projects/UAPK/build/dist/providers/fdroid.js:63:36)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0
| node             | linux-x86-12.9.1
| npm              | yarn 1.22.10
| Operating System | `Linux fedora 5.13.12-201.fsync.fc34.x86_64 #1 SMP Mon Aug 23 21:11:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

Nothing

**Comment by jimmywarting** [comment]
you need to have `"type": "module"` in package.json.

**Comment by jimmywarting** [comment]
and also compile to esm

**Comment by pjalsGit** [comment]
welp now im getting 100x more issues which are not by this package but thanks!
