### ISSUE TITLE
issue with ts jest and node-fetch v3

### ISSUE THREAD

**Issue by akdj** [node-fetch/node-fetch#1289]
I upgraded node-fetch to v3, and run jest test and I get: 

```
 Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:
import http from 'http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Task, DataError } from '@koober/std';
    > 2 | import fetch from 'node-fetch';
        | ^
      3 | import { FacebookResponseError, FacebookTokenInfo, FacebookTokenInfoFormatted, FacebookUserIdentity } from './data';
      4 |
      5 | export interface FacebookClient

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1597:14)
      at Object.<anonymous> (src/bundle/facebook/client.ts:2:1)
  ```
  
  I followed instructions, but nothing changes, 
  I also tried  this jest config 
  ```
....
  "extensionsToTreatAsEsm": [
      ".ts"
    ],
    "globals": {
      "ts-jest": {
        "tsconfig": "tsconfig.json",
        "useESM": true
      }
    },
     "preset": "ts-jest/presets/default-esm",
....
    ```
    but nothing happens

**Comment by sorensenNiels** [comment]
Any idea on the subject - I have the same problem have reverted to v2.6.1 and started migration to axios.

**Comment by jimmywarting** [comment]
ping @LinusU you have some more experiences with jest, maybe you have any suggestions?

**Comment by tomas-hartman** [comment]
+1 same issue with ts/jest compiled with babel

**Comment by berenddeboer** [comment]
Having the same problem here.

**Comment by JulienKode** [comment]
I experience the same issue on my side with swc

**Comment by storyalex** [comment]
I have a few typescript projects where this happened to me.

Add the following to `jest.config.js` to run all .js-files through babel when running jest:
```js
  transform: {
    "^.+\\.(ts|tsx)$": "ts-jest",
    "^.+\\.(js)$": "babel-jest",
  },
  transformIgnorePatterns: [
  ],
```

Note the empty `transformIgnorePatterns`. By default transforms ignore node_modules.
This worked for me with:

node-fetch: ^3.0.0
babel-jest: ^27.3.1
jest: ^27.3.1
ts-jest: ^27.0.7

**Comment by sun293529884** [comment]
I put this in my package.json, but dint work..., I had rollback the version from "node-fetch": "^3.1.0", to "node-fetch": "^2.6.0",
it works well...
```JSON
  "jest": {
    "verbose": true,
    "extraGlobals": [
      "Math"
    ],
    "setupFilesAfterEnv": [
      "./lib/fix-return-warning.js"
    ],
    "testMatch": [
      "**/*.spec.js"
    ],
    "transform": {
      "^.+\\.(js)$": "babel-jest"
    },
    "transformIgnorePatterns": []
  },
```

**Comment by martsie** [comment]
Rolling back to 2.6 worked for me to get serverless-bundle to run jest tests.

**Comment by bertrand-caron** [comment]
Has anyone made any progress on this? I tried @lynxtaa's solution with no success.

**Comment by ccarcaci** [comment]
Same here, rolling back to 2.6 worked. Any of the other solutions were not working.

**Comment by p0wl** [comment]
same issue here, rolled back as well...

**Comment by rguzg** [comment]
rolling back worked as well!

**Comment by brunobmello25** [comment]
To those who are rolling back, how are you using the type definitions? node-fetch@2 doesn't ship with type definitions and installing @types/node-fetch doesn't seem to solve my problem.

Here is how I am importing the module

![image](https://user-images.githubusercontent.com/29875060/148814451-763c57a7-3d24-41e5-ad5d-7682db554f48.png)

And in my package.json I have listed both @types/node-fetch on devDependencies and node-fetch on dependencies

```
{
  ...
  "devDependencies": {
    ...
    "@types/node-fetch": "^3.0.3",
    ...
  },
  "dependencies": {
    ...
    "node-fetch": "^2.6.6",
    ...
  }
}

```

**Comment by brunobmello25** [comment]
To those who are rolling back, how are you using the type definitions? node-fetch@2 doesn't ship with type definitions and installing @types/node-fetch doesn't seem to solve my problem.

Here is how I am importing the module

![image](https://user-images.githubusercontent.com/29875060/148815017-8c454672-f440-4387-b6a5-baf93e2f3628.png)

And in my package.json I have listed both @types/node-fetch on devDependencies and node-fetch on dependencies

```
{
  ...
  "devDependencies": {
    ...
    "@types/node-fetch": "^3.0.3",
    ...
  },
  "dependencies": {
    ...
    "node-fetch": "^2.6.6",
    ...
  }
}

```

**Comment by rguzg** [comment]
As typing information is already included in node-fetch 3.0 and up,
the @types/node-fetch package after version 3.0 is just a stub. To get
typing information you need to install a version of the types package
that's inside the 2.x range. In my case, I installed version 2.5.12 and
everything's working fine.

**Comment by mikeaustin** [comment]
Is there a solution to using node-fetch 3.x with jest?

**Comment by veritem** [comment]
I ended up using this library https://github.com/nodejs/undici. it works like a charm.

**Comment by ksw25** [comment]
Is there a solution for this?

**Comment by ravshansbox** [comment]
This is a small example where jest works with node-fetch@3: https://github.com/ravshansbox/jest-node-fetch-es-modules

**Comment by plemelin** [comment]
> This is a small example where jest works with node-fetch@3: https://github.com/ravshansbox/jest-node-fetch-es-modules

This is misleading as it works only because you are telling jest to run with support for ESM (--experimental-vm-modules). 

As far as I can tell, node-fetch v3 only works as an ESM and you cannot make it work in jest without that flag. Our teams are not going to use that flag unfortunately. So unless this becomes supported in Jest, we are going to use node-fetch <3.0.0

Also looks like it's slowing the adoption of  node-fetch v3:

![Screenshot from 2022-02-09 15-07-41](https://user-images.githubusercontent.com/38959411/153282564-84027f94-37d0-4b1d-8445-365721512ddf.png)
