### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by ImperatorOfIntellectualism** [node-fetch/node-fetch#1357]
Trying to make your lib work, but have a couple of problems
Problem one:
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\CODE\node_modules\node-fetch\src\index.js
require() of ES modules is not supported.
require() of D:\CODE\node_modules\node-fetch\src\index.js from D:\CODE\dist\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename D:\CODE\node_modules\node-fetch\src\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\CODE\node_modules\node-fetch\package.json.

At the end of the log it has some instructions, I followed it but it has another error:
TypeError: (0 , node_fetch_1.default) is not a function
    at D:\CODE\dist\index.js:30:34
    at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CODE\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\CODE\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
    at D:\CODE\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\CODE\node_modules\express\lib\router\index.js:335:12)
    at next (D:\CODE\node_modules\express\lib\router\index.js:275:10)
    at D:\CODE\dist\index.js:27:9
    at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CODE\node_modules\express\lib\router\index.js:317:13)
    at D:\CODE\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\CODE\node_modules\express\lib\router\index.js:335:12)
    at next (D:\CODE\node_modules\express\lib\router\index.js:275:10)
    at D:\CODE\node_modules\express\lib\router\index.js:635:15
    at next (D:\CODE\node_modules\express\lib\router\index.js:260:14)

**Reproduction**
Just trying to fetch with your lib, doesn't work. You might be interested to hear that I use TS, and I have something called tsc - watch that converts TS code to JS, this might have something to do with the problems above.

**Expected behavior**
It should work.

Hope you can fix this soon.

**Comment by jimmywarting** [comment]
node-fetch@3 is esm-only
you  can not use require to import it.

https://github.com/node-fetch/node-fetch/issues/1279

**Comment by ImperatorOfIntellectualism** [comment]
You didn't read my post. I'm already not using require.

Here is my code:
const node_fetch_1 = __importDefault("../node_modules/node-fetch");
 (0, node_fetch_1.default)('FETCHING ADDRESS', {
            method: "POST",
            headers: {
                Accept: "application/json",
                'Content-Type': 'multipart/form-data',
            },
            body: req.body
        });

It gives:
TypeError: (0 , node_fetch_1.default) is not a function
at D:\CODE\dist\index.js:30:34
at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
at next (D:\CODE\node_modules\express\lib\router\route.js:137:13)
at Route.dispatch (D:\CODE\node_modules\express\lib\router\route.js:112:3)
at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
at D:\CODE\node_modules\express\lib\router\index.js:281:22
at Function.process_params (D:\CODE\node_modules\express\lib\router\index.js:335:12)
at next (D:\CODE\node_modules\express\lib\router\index.js:275:10)
at D:\CODE\dist\index.js:27:9
at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (D:\CODE\node_modules\express\lib\router\index.js:317:13)
at D:\CODE\node_modules\express\lib\router\index.js:284:7
at Function.process_params (D:\CODE\node_modules\express\lib\router\index.js:335:12)
at next (D:\CODE\node_modules\express\lib\router\index.js:275:10)
at D:\CODE\node_modules\express\lib\router\index.js:635:15
at next (D:\CODE\node_modules\express\lib\router\index.js:260:14)

Are you going to do something about it or no?

**Comment by jimmywarting** [comment]
1. what dose `__importDefault` do?
2. why do you use `"../node_modules/node-fetch"` and not just `"node-fetch"`?

try this:
```js
const _importDynamic = new Function('modulePath', 'return import(modulePath)')

async function fetch(...args) {
  const {default: fetch} = await _importDynamic('node-fetch'))
  return fetch(...args))
}
```

**Comment by jimmywarting** [comment]
the alternative is if you transpile your typescript code to esm as well https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-rc/

**Comment by ImperatorOfIntellectualism** [comment]
Did it, 
const _importDynamic = new Function('modulePath', 'return import(modulePath)')
async function fetch(...args) {
  const {default: fetch} = await _importDynamic('../node_modules/node-fetch')
  return fetch(...args)
}
The reason why I'm using '../node_modules/node-fetch' is because it can't find it otherwise.

(node:2204) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'D:\CODE\node_modules\node-fetch' is not supported resolving ES 
modules imported from D:\CODE\dist\index.js
    at finalizeResolution (internal/modules/esm/resolve.js:267:17)
    at moduleResolve (internal/modules/esm/resolve.js:694:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at Loader.import (internal/modules/esm/loader.js:176:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at eval (eval at <anonymous> (D:\CODE\dist\index.js:16:24), <anonymous>:3:1)
    at fetch (D:\CODE\dist\index.js:18:34)
    at D:\CODE\dist\index.js:34:9
    at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CODE\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\CODE\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\CODE\node_modules\express\lib\router\layer.js:95:5)
    at D:\CODE\node_modules\express\lib\router\index.js:281:22

**Comment by jimmywarting** [comment]
> The reason why I'm using `'../node_modules/node-fetch'` is because it can't find it otherwise.

This is the problem... you shouldn't have to do `'../node_modules/` then you are probably standing in the wrong working directory. Or you haven't installed the dependency
if anything then it should be `../node_modules/node-fetch/src/index.js` but you shouldn't have to do this...

i just tried my above suggestion to make sure that it did work, and it did...
```
npm init -y
npm i node-fetch
node -e "new Function('modulePath', 'return import(modulePath)')('node-fetch').then(console.log)"
```
also tried sticking the code in a js file and executing `node ./index.js`

**Comment by ImperatorOfIntellectualism** [comment]
Do you know of any library that allows fetching in Node js but actually works?

**Comment by jimmywarting** [comment]
> Do you know of any library that allows fetching in Node js but actually works?

Pretty much all of this: https://github.com/search?o=desc&q=%22import%28%27node-fetch%27%29%22&s=indexed&type=Code

**Comment by jimmywarting** [comment]
please try to recreate a minimal reproduction of all the tools (typescript, npm, node, yarn), commands, files  etc you are using and what version you are also using so i can reproduce the error

> Just trying to fetch with your lib, doesn't work. You might be interested to hear that I use TS, and I have something called tsc - watch that converts TS code to JS, this might have something to do with the problems above.

This information alone is not enough to reproduce the error you encounter. A github project or zip file would be helpful

**Comment by ImperatorOfIntellectualism** [comment]
Just for YOU I uploaded my project to GitHub. https://github.com/ImperatorOfIntellectualism/CHANapp/tree/main/KEKW
Instructions:
"npm run test" for backend
"npm run dev" in folder chanapp for frontend.

**Comment by LinusU** [comment]
@ImperatorOfIntellectualism here is a diff that makes it work for me:

```diff
diff --git a/KEKW/package.json b/KEKW/package.json
index 7ed9245..e787c74 100644
--- a/KEKW/package.json
+++ b/KEKW/package.json
@@ -3,10 +3,11 @@
   "version": "1.0.0",
   "description": "",
   "main": "index.js",
+  "type": "module",
   "scripts": {
     "watch": "tsc -w",
-    "test": "nodemon dist/index.js",
-    "start": "ts-node src/index.ts",
+    "test": "NODE_OPTIONS=--experimental-specifier-resolution=node nodemon dist/index.js",
+    "start": "node --loader ts-node/esm --experimental-specifier-resolution=node src/index.ts",
     "migration": "mikro-orm migration:create"
   },
   "author": "",
diff --git a/KEKW/src/index.ts b/KEKW/src/index.ts
index f0ae144..19854f4 100644
--- a/KEKW/src/index.ts
+++ b/KEKW/src/index.ts
@@ -9,7 +9,7 @@ import { PostResolver } from './resolvers/post';
 import { UserResolver } from './resolvers/user';
 import { ThreadResolver } from './resolvers/thread';
 import { BoardResolver } from './resolvers/board';
-import fetch from '../node_modules/node-fetch';
+import fetch from 'node-fetch';
 
 //Persist And Flush - adds model to the table
 
@@ -18,7 +18,7 @@ const main = async ( ) => {
     const apolloServer = new ApolloServer({schema: await buildSchema({resolvers: [HelloResolver, PostResolver, UserResolver, ThreadResolver, BoardResolver], validate: false}), context: () => ({em: orm.em})})
     await apolloServer.start();
     apolloServer.applyMiddleware({app})
-    const orm = await MikroORM.init(config) 
+    const orm = await MikroORM.init(config)
     await orm.getMigrator().up()
 
     app.use(function(_, res, next) {
diff --git a/KEKW/src/mikro-orm.config.ts b/KEKW/src/mikro-orm.config.ts
index 32c7316..28a0ee7 100644
--- a/KEKW/src/mikro-orm.config.ts
+++ b/KEKW/src/mikro-orm.config.ts
@@ -1,14 +1,14 @@
 import { __prod__ } from "./constants";
 import { Post } from "./entities/Post";
 import { MikroORM } from "@mikro-orm/core";
-import path from 'path'
 import { User } from "./entities/User";
 import { Thread } from "./entities/Thread";
 import { Board } from "./entities/Board";
+import { URL, fileURLToPath } from "url";
 
 export default {
     migrations: {
-      path: path.join(__dirname + '/migrations'), // path to the folder with migrations
+      path: fileURLToPath(new URL('migrations', import.meta.url)), // path to the folder with migrations
       pattern: /^[\w-]+\d+\.[tj]s$/, // regex pattern for the migration files
     },
     entities: [Post, User, Thread, Board],
diff --git a/KEKW/tsconfig.json b/KEKW/tsconfig.json
index 3b3e51b..2e4b5f1 100644
--- a/KEKW/tsconfig.json
+++ b/KEKW/tsconfig.json
@@ -1,7 +1,7 @@
 {
   "compilerOptions": {
     "target": "es2017",
-    "module": "commonjs",
+    "module": "ES2020",
     "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
     "skipLibCheck": true,
     "sourceMap": true,
```


With this both `ts-node` for running the TS files directly and `nodemon` on the built files works.

-----

`--experimental-specifier-resolution=node` is needed because you aren't specifying a file extension when importing files. That is `import config from './mikro-orm.config'` instead of `import config from './mikro-orm.config.js'`. I would recommend adding the file extension to the import, since that seems to be what Node.js is recommending going forward.

**Comment by jimmywarting** [comment]
agree, using extension is the new de-facto way of writing modules. that way Deno, Browser and node's new http-loader can automatically resolve the path from a remote place where it don't have access to the filesystem and can't automatically figure out what the path is

So i also recommend that you use extension and avoid using `experimental-specifier-resolution` 

sindre have some guide/gist on writing esm: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ImperatorOfIntellectualism** [comment]
``internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'D:\CODE\kekw\node_modules\node-fetch\' imported from D:\CODE\kekw\dist\index.js
    at legacyMainResolve (internal/modules/esm/resolve.js:220:9)
    at packageResolve (internal/modules/esm/resolve.js:643:14)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_MODULE_NOT_FOUND'``

Look, I think it's just your thing with "NO ESM" or whatever is causing this. Your library doesn't work, just admit it.
Answer me this: Why does every single other library work perfectly while yours doesn't work after multiple days of talking to you?
It shouldn't be this hard, your library doesn't even do anything crazy.

**Comment by ImperatorOfIntellectualism** [comment]
And before you ask, yes I obviously do have your library installed. But something is preventing it from being used and I'm sure it's your thing

>node-fetch@3 is esm-only
>you can not use require to import it.

that is the problem. In the end it just doesn't work.

**Comment by jimmywarting** [comment]
> Look, I think it's just your thing with "NO ESM" or whatever is causing this. Your library doesn't work, just admit it.
Answer me this: Why does every single other library work perfectly while yours doesn't work after multiple days of talking to you?
It shouldn't be this hard, your library doesn't even do anything crazy.

Don't take it so harsh, you may have perhaps tried to make it work with esm for days, but you only started this thread yesterday. And we are trying to help you.
Many are already using node-fetch@3 already in their project and it's working for them.

Both @LinusU and I have given you suggestion/patches and we both have made it work with node-fetch@3 in your project with positive outcome 

The reason why other packages most likely works are b/c they might very possible be written in old commonjs-style or they write it in such a way that it has dual support for both esm and cjs where as we only support esm

> > node-fetch@3 is esm-only
> > you can not use require to import it.
> 
> that is the problem. In the end it just doesn't work.

That is intentional, we no longer support commonjs `require()` or dual support due to complexity, size and problem with instanceof checks
esm is the feature. If you don't want to deal with ESM then you can still use v2.x. version 2 is written with commonjs and will still get security fixes, but not so much new features. but it's recommended to also use v3 and also switching to esm

> your library doesn't even do anything crazy.

Then why don't you just use nodes built in http module? The fetch api is huge and complex and have many web components and spec-rules to follow, so it isn't not just a fly.

it's still very much possible to import esm-only packages from a commonjs project without having to switch to esm yourself. 

Why you are geting `ERR_MODULE_NOT_FOUND`, `ERR_UNSUPPORTED_DIR_IMPORT`, `ERR_REQUIRE_ESM` is not our fault. We are trying to help but are unable to reproduce the error after the patch we have suggested to you

So there is not something we must in node-fetch do to fix this. Even more so when it's already working for others and with this simple cjs demonstration created out of nothing:
```bash
npm init -y # initialise a cjs project
npm i node-fetch # install latest node-fetch built with esm

# testing if lazy import works, which it dose
node -e "import('node-fetch').then(console.log)"

# testing a solution that prevent typescript from rewriting import to require, that also works
node -e "new Function('mod', 'return import(mod)')('node-fetch').then(console.log)"
```

**Comment by jimmywarting** [comment]
do you use a up-to-date nodejs version?

**Comment by LinusU** [comment]
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'D:\CODE\kekw\node_modules\node-fetch' imported from D:\CODE\kekw\dist\index.js

I was able to run it with the changes I made.

Are you sure that you applied all the changes? It looks like you didn't change `import fetch from '../node_modules/node-fetch'` to `import fetch from 'node-fetch'`.

> Your library doesn't work, just admit it.

😂 

If you want some help try and be a bit nice about it...

**Comment by ImperatorOfIntellectualism** [comment]
Ok, you did something with the way my imports work, it now says this under most of my imports
![image](https://user-images.githubusercontent.com/83208504/140378723-d1cc5de4-3a1b-4721-9312-11084564648c.png)

The way to fix this is by adding JS to the import
import config from './mikro-orm.config'; => import config from './mikro-orm.config.js';
And it starts working.
I have the same error with your library.
![image](https://user-images.githubusercontent.com/83208504/140378989-9f8b8e94-ea64-41e5-8ae8-ce4d7c5a0b0b.png)

You are so incompetent that you literally made my code WORSE than it was. Are you going to fix it? I updated the repository.

**Comment by LinusU** [comment]
> You are so incompetent that you literally made my code WORSE than it was. Are you going to fix it? I updated the repository.

Well, after that comment I personally won't be helping you with anything...

**Comment by jimmywarting** [comment]
we don't tolerate this
