### ISSUE TITLE
TypeError: fetch is not a function

### ISSUE THREAD

**Issue by maverick-dev-55** [node-fetch/node-fetch#1407]
my code was just working at least 5 hours ago and now is giving me this error
```
TypeError: fetch is not a function
    at Object.<anonymous> (D:\Projects\PaintBot\libs\mc.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Projects\PaintBot\commands\about.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

```js
const fetch = import('node-fetch')
const getUUID = async function(un){
    let uuid
    await fetch(`https://api.mojang.com/users/profiles/minecraft/${un}`)
    .then(res=>res.json())
    .then(json=>{
        try {
            uuid = {result: true, uuid: json.id}
        } catch {
            uuid = {result: false, uuid: null}
        }
    })
    return uuid
}
```

this code is supposed to just return the result and id but instead, it says fetch isn't a function, am I doing something wrong?

### My Environment

| software         | version
| ---------------- | -------
| node-fetch       | 3.1.0
| node             | 16.11.1
| npm              | 8.0.0
| Operating System | Microsoft Windows [Version 10.0.19044.1348]

**Comment by LinusU** [comment]
`fetch` in your code is a `Promise` of the actual module, since you are calling the `import` function which is async. Could you try the following change:

```diff
- const fetch = import('node-fetch')
+ import fetch from 'node-fetch'
```

**Comment by cjh980402** [comment]
Use `import fetch from 'node-fetch'` on top of code.
However, if you want import fetch in function then,
use `const fetch = (await import('node-fetch')).default;` in function.

**Comment by jimmywarting** [comment]
as an 3th alt option here is top level await import inside the fuction
```js
async function getUUID (un) {
  const url = `https://api.mojang.com/users/profiles/minecraft/${un}`
  try {
    const { default: fetch } = await import('node-fetch')
    const res = await fetch(url)
    const json = await res.json()
    return { result: true, uuid: json.id }
  } catch (err) {
    return { result: false, uuid: null }
  }
}
```

**Comment by maverick-dev-55** [comment]
Fixed!
Here is the code:
```js
const fetch = import('node-fetch')
const getUUID = async function(un){
    let uuid
    await fetch.then(async data=>{
        await data.default(`https://api.mojang.com/users/profiles/minecraft/${un}`)
        .then(res=>res.json())
        .then(json=>{
            try {
                uuid = {result: true, uuid: json.id}
            } catch {
                uuid = {result: false, uuid: null}
            }
        })
    })
    return uuid
}
```

**Comment by maverick-dev-55** [comment]
not me only seeing the comments when I comment.
Thanks for the help tho

**Comment by jimmywarting** [comment]
vscode (typescript) will have a harder time of knowing what the return type is if you assign uuid later like that...
it's better to have a return instead.

few examples if you want to keep import at top:
```js
const fetch = import('node-fetch')

const getUUID = async function(un){
    const uuid = await fetch.then(async data=>{
        return data.default(`https://api.mojang.com/users/profiles/minecraft/${un}`)
        .then(res=>res.json())
        .then(json=>{
            try {
              return { result: true, uuid: json.id }
            } catch {
              return { result: false, uuid: null }
            }
        })
    })
    return uuid
}
```
```js
const fetch = import('node-fetch')

const getUUID = function(un){
  return fetch.then(data => {
    return data.default(`https://api.mojang.com/users/profiles/minecraft/${un}`)
    .then(res => res.json())
    .then(json => {
      try {
        return { result: true, uuid: json.id }
      } catch {
        return { result: false, uuid: null }
      }
    })
  })
}
```

```js
const fetch = import('node-fetch')

const getUUID = un => fetch
  .then(({default: fetch}) => fetch(`https://api.mojang.com/users/profiles/minecraft/${un}`))
  .then(res => res.json())
  .then(json => {
    try {
      return { result: true, uuid: json.id }
    } catch {
      return { result: false, uuid: null }
    }
  })
```
```js
const fetch = import('node-fetch')

const getUUID = un => fetch
  .then(({ default: fetch }) => fetch(`https://api.mojang.com/users/profiles/minecraft/${un}`))
  .then(res => res.json())
  .then(json => ({ result: true, uuid: json.id }))
  // fallback if any of the above fails (load module, parse json, or get id of json)
  .catch(err => ({ result: false, uuid: null }))
```

```js
const fetch = import('node-fetch')

const getUUID = async function (un) {
  const url = `https://api.mojang.com/users/profiles/minecraft/${un}`
  const { default: _fetch } = await fetch
  const res = await _fetch(url)
  const json = await res.json()

  try {
    return { result: true, uuid: json.id }
  } catch (err) {
    return { result: false, uuid: null }
  }
}
```
