### ISSUE TITLE
jest: open handle detected

### ISSUE THREAD

**Issue by lfantone** [node-fetch/node-fetch#1479]
Hi all, I would like to report a strange behaviour that started to happen after upgrading to the latest release.
When running our test suite, I noticed a warning message after completion saying:

```bash
Ran all test suites matching /src/i.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  MESSAGEPORT

      at Object.<anonymous> (../../node_modules/node-domexception/index.js:6:12)
          at async Promise.all (index 16)
          at async Promise.all (index 3)
          at async Promise.all (index 1)
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (../../node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (../../node_modules/@jest/core/build/cli/index.js:173:3)
```

Doing a rollback to `node-fetch@3.1.1` makes the warning disappear. I would assume that something has changed in the latest release that is causing this issue. 

**Reproduction**

Steps to reproduce the behaviour:

1. Create a test file that uses `node-fetch`
2. Run the test with `jest`

**Expected behaviour**

I would expect to not have any warning/error in the jest output

**Screenshots**

![image](https://user-images.githubusercontent.com/850110/150777842-93e807f7-1bd0-4f84-bf43-12b90d961a14.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | v3.2.0
| node             | v16.13.0
| npm              | 8.1.0
| Operating System | macOs Monterey 12.1

**Comment by lfantone** [comment]
I created a test repository, you can find it [here](https://github.com/lfantone/node-fetch-jest).
I also try to set up the same under the [stackblitz](https://stackblitz.com/edit/node-unocmn) link you shared but seems that the node version is 14 I wasn't able to run the test with jest.
Let me know if you need more information, happy to help :)

**Comment by apoco** [comment]
For what it's worth I'm also experiencing this with `node-fetch@2.6.7` and `node@16.13.0`.

```
Jest has detected the following 5 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      187 |
      188 |     it("fails with a 404 if the category does not exist", async () => {
    > 189 |       const res = await fetch(`${url}/999999`, {
          |                              ^
      190 |         agent,
      191 |         method: "PATCH",
      192 |         headers: {

      at node_modules/node-fetch/lib/index.js:1468:15
      at fetch (node_modules/node-fetch/lib/index.js:1437:9)
      ...
 ```

**Comment by kopax-polyconseil** [comment]
Did you solve it? We also have the same issue:

```
Jest has detected the following 3 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      17 |   const url = `${href}${API_BASE_PATH_NATIVE_V1}/${entityValue.NAME}/${id}`
      18 |
    > 19 |   const response = await fetch(url, {
         |                          ^
      20 |     headers: new Headers({
      21 |       'cache-control': 'public,max-age=3600',
      22 |     }),

      at new NodeClientRequest (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:63:5)
      at node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/http.request.ts:24:12
      at node_modules/node-fetch/lib/index.js:1468:15
      at fetch (node_modules/node-fetch/lib/index.js:1437:9)
      at fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
      at apiClient (src/services/apiClient.ts:19:26)
      at Object.<anonymous> (src/services/tests/apiClient.test.tsx:7:25)


  ●  TLSWRAP

      17 |   const url = `${href}${API_BASE_PATH_NATIVE_V1}/${entityValue.NAME}/${id}`
      18 |
    > 19 |   const response = await fetch(url, {
         |                          ^
      20 |     headers: new Headers({
      21 |       'cache-control': 'public,max-age=3600',
      22 |     }),

      at new NodeClientRequest (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:63:5)
      at node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/http.request.ts:24:12
      at node_modules/node-fetch/lib/index.js:1468:15
      at fetch (node_modules/node-fetch/lib/index.js:1437:9)
      at fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
      at apiClient (src/services/apiClient.ts:19:26)
      at Object.<anonymous> (src/services/tests/apiClient.test.tsx:12:25)


  ●  TLSWRAP

      17 |   const url = `${href}${API_BASE_PATH_NATIVE_V1}/${entityValue.NAME}/${id}`
      18 |
    > 19 |   const response = await fetch(url, {
         |                          ^
      20 |     headers: new Headers({
      21 |       'cache-control': 'public,max-age=3600',
      22 |     }),

      at new NodeClientRequest (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:63:5)
      at node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/http.request.ts:24:12
      at node_modules/node-fetch/lib/index.js:1468:15
      at fetch (node_modules/node-fetch/lib/index.js:1437:9)
      at fetch (node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
      at apiClient (src/services/apiClient.ts:19:26)
      at src/services/tests/apiClient.test.tsx:24:36
      at Object.toThrowError (node_modules/expect/build/index.js:267:58)
      at Object.<anonymous> (src/services/tests/apiClient.test.tsx:24:67)

```

**Comment by molily** [comment]
Hi, is there a potential fix or workaround for this issue? The minimal test case above still produces an error with the latest Jest and node-fetch. Thanks.

**Comment by oscar0206** [comment]
upgrade jest from 27.0.3 to 29.4.3 and ts-jest from 28.0.1 to 29.0.5 fix my problem

**Comment by tada5hi** [comment]
any news on that ?

**Comment by kasir-barati** [comment]
Experiencing same issue, but https://github.com/node-fetch/node-fetch/issues/1479#issuecomment-1171549725 is like a struck of lightening. Not sure but will try to see if something is missing in my backend code though I doubt it :/.
