### ISSUE TITLE
Fetch is not a function 

### ISSUE THREAD

**Issue by R0N1n-dev** [node-fetch/node-fetch#1575]
V2.6.7 is not working with require.
Throws error of 'fetch is not a function'.
Followed docs.

**Comment by LinusU** [comment]
You need to provide a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), there is not enough info for us to help you here...

**Comment by R0N1n-dev** [comment]
```const express = require("express");
const fetch = import("node-fetch");
const redis = require("redis");

const port = process.env.PORT || 3000;
const REDIS_PORT = process.env.REDIS_PORT || 6379;

const client = redis.createClient(REDIS_PORT);
const app = express();

async function getRepos(req, res, next) {
  try {
    console.log("Fetching data ....");
    const { username } = req.params;
    const response = await fetch(`https://api.github.com/users/${username}`);
    const data = await response.json();
    res.send(data);
  } catch (error) {
    console.error(error);
    res.status(500);
  }
}

app.get("/repos/:username", getRepos);
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
```



**Console Error**
ronin@ronin-HP-Laptop:~/red-cache$ node index
Example app listening on port 3000!
Fetching data ....
TypeError: fetch is not a function
    at getRepos (/home/ronin/red-cache/index.js:15:28)
    at Layer.handle [as handle_request] (/home/ronin/red-cache/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ronin/red-cache/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/ronin/red-cache/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/ronin/red-cache/node_modules/express/lib/router/layer.js:95:5)
    at /home/ronin/red-cache/node_modules/express/lib/router/index.js:284:15
    at param (/home/ronin/red-cache/node_modules/express/lib/router/index.js:365:14)
    at param (/home/ronin/red-cache/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/home/ronin/red-cache/node_modules/express/lib/router/index.js:421:3)
    at next (/home/ronin/red-cache/node_modules/express/lib/router/index.js:280:10)


deps
 "dependencies": {
    "express": "^4.18.1",
    "node-fetch": "^2.6.7",
    "redis": "^4.1.0"
  }



Env
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Package Manager:  `npm@8.5.5`

**Comment by LinusU** [comment]
Did you mean to use require here?

```diff
- const fetch = import("node-fetch");
+ const fetch = require("node-fetch");
```
