### ISSUE TITLE
Cannot read properties of null (reading, 'body'). regression in 2.6.7

### ISSUE THREAD

**Issue by shannah** [node-fetch/node-fetch#1700]
Just reporting this bug upstream that we've run across in crowdin.

https://github.com/crowdin/crowdin-cli/issues/523

```bash
Downloading java runtime environment for version 11
/Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1519
			destroyStream(response.body, err);
			                       ^

TypeError: Cannot read properties of null (reading 'body')
    at /Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/Users/shannah/.npm/_npx/e624e2fddcf46226/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:527:28)
    at emitCloseNT (node:internal/streams/destroy:138:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This issue doesn't appear to happen using 2.6.7

To reproduce, you can just create an empty directory and run `npx @crowdin/cli@3.9.2`

**Comment by Fonnte** [comment]
yeah, i also experience this after updating to 2.6.7

`TypeError: Cannot read properties of null (reading 'body')
    at /user/production/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/user/production/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)`

**Comment by Fleker** [comment]
I've run into this on 2.6.8 as well. After downgrading to 2.6.7 things worked as expected.

**Comment by abhinav-saini** [comment]
An old bug in case of a redirect seems to be reintroduced in this version 2.6.8 -  #1222

**Comment by Danrejk** [comment]
I also have this issue

**Comment by SelinR** [comment]
Also met such problem. Returned to 2.6.7 version - and it fixed it.
