### ISSUE TITLE
Bug with 2.6.8 release throwing exceptions in certain cases

### ISSUE THREAD

**Issue by roptch** [node-fetch/node-fetch#1701]
Hello,
Recently, we found a bug that was introduced by [release 2.6.8](https://github.com/node-fetch/node-fetch/releases/tag/v2.6.8) (probably due to [this PR](https://github.com/node-fetch/node-fetch/pull/1172)) that makes node-fetch throw an error in some cases.
I was not able to determine why, but it is simple to reproduce.
Here is the exception:
```sh
/Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1519
			destroyStream(response.body, err);
			                       ^

TypeError: Cannot read properties of null (reading 'body')
    at /Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/Users/mainrop/Documents/node-fetch-2-6-8-bug/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Reproduction**

Here is a repository I made to reproduce this issue: https://github.com/roptch/node-fetch-2-6-8-bug

1. Clone the repo
2. `nvm use` (the node version in this repo is 16, but also tested with 12 and 18 and the error keeps throwing)
3. `yarn start`
4. See the exception that is thrown

**Expected behavior**

No exception should be thrown.

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.8
| node             | 16.18.0
| npm              | 8.19.2
| Operating System | macOS Big Sur (11.6.7)

**Additional context**

**Comment by kevinxh** [comment]
This happened on my project as well for version `2.6.8`

**Comment by NewEraCracker** [comment]
Can reproduce the same issue
```
TypeError: Cannot read property 'body' of null
    at node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at TLSSocket.socketCloseListener (_http_client.js:441:11)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
  ```
 
 Culprit seems to be:
 ```
 		fixResponseChunkedTransferBadEnding(req, function (err) {
			if (signal && signal.aborted) {
				return;
			}

			destroyStream(response.body, err);
		});
```
Could the `destroyStream` call be protected with
```
			if (response && response.body) {
				destroyStream(response.body, err);
			}
```
Like is done above?

**Comment by ilg-ul** [comment]
I'm seeing something similar, with 2.6.8 in `xpm`, a tool that extends `npm`:

```console
2023-01-28T11:21:13.2651220Z Downloading https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v12.2.0-2/xpack-gcc-12.2.0-2-linux-x64.tar.gz...
2023-01-28T11:21:13.5857074Z /usr/local/lib/node_modules/xpm/node_modules/node-fetch/lib/index.js:1519
2023-01-28T11:21:13.5858869Z 			destroyStream(response.body, err);
2023-01-28T11:21:13.5859935Z 			                       ^
2023-01-28T11:21:13.5860218Z 
2023-01-28T11:21:13.5860733Z TypeError: Cannot read properties of null (reading 'body')
2023-01-28T11:21:13.5861518Z     at /usr/local/lib/node_modules/xpm/node_modules/node-fetch/lib/index.js:1519:27
2023-01-28T11:21:13.5862827Z     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/xpm/node_modules/node-fetch/lib/index.js:1749:6)
2023-01-28T11:21:13.5863482Z     at Object.onceWrapper (node:events:627:28)
2023-01-28T11:21:13.5863978Z     at IncomingMessage.emit (node:events:513:28)
2023-01-28T11:21:13.5864467Z     at IncomingMessage.emit (node:domain:489:12)
2023-01-28T11:21:13.5864972Z     at emitCloseNT (node:internal/streams/destroy:138:10)
2023-01-28T11:21:13.5865569Z     at processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-01-28T11:21:13.6753671Z ##[error]Process completed with exit code 1.
```

At the time when this happened, it looks like the GitHub server experienced some problems, since another parallel GitHub Actions job also failed, but with a civilised error:

```console
2023-01-28T11:21:28.4173512Z debug: fetch.status 200 https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v12.2.0-2/xpack-gcc-12.2.0-2-linux-arm.tar.gz
2023-01-28T11:21:28.4178101Z trace: fetch.statusText OK https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v12.2.0-2/xpack-gcc-12.2.0-2-linux-arm.tar.gz
2023-01-28T11:21:28.4181812Z trace: create write stream for xpm:binaries:xpack-gcc-12.2.0-2-linux-arm.tar.gz
2023-01-28T11:21:28.4187424Z trace: create pipeline for xpm:binaries:xpack-gcc-12.2.0-2-linux-arm.tar.gz
2023-01-28T11:21:29.3022848Z trace: Error: read ECONNRESET
2023-01-28T11:21:29.3029113Z read ECONNRESET
2023-01-28T11:21:29.3045976Z error: download failed, quit
2023-01-28T11:21:29.3052972Z exit(3)
2023-01-28T11:21:29.3478632Z ##[error]Process completed with exit code 3.
```

A 2.6.9 would be highly appreciated!

Thank you!

**Comment by ilg-ul** [comment]
@segevfiner, thank you for fixing this so quickly!
