### ISSUE TITLE
fetch syntaxError unexpected identifier with babel

### ISSUE THREAD

**Issue by dominikabieder** [node-fetch/node-fetch#720]
I have been using ES6 import syntax for a while in the project, but since I've installed node-fetch I keep getting the error below, than only goes away when I change the import to const fetch = require('node-fetch') instead.

 ```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import fetch from 'node-fetch'; // const fetch = require('node-fetch')
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

```

I've had babel installed before and it worked fine with the import syntax. 

```
},
  "devDependencies": {
    "@babel/cli": "7.7.5",
    "@babel/core": "7.7.5",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0",
    "@babel/plugin-transform-runtime": "7.7.6",
    "@babel/preset-env": "7.7.6",
    "babel-eslint": "10.0.3",
    "babel-loader": "8.0.6",
    "eslint": "6.7.2",
    "eslint-plugin-import": "2.19.1",
    "eslint-watch": "6.0.1",
    "jest": "^24.9.0",
    "serverless": "1.59.3",
    "serverless-offline": "5.12.1",
    "serverless-webpack": "5.3.1",
    "source-map-support": "0.5.16",
    "webpack": "4.41.2",
    "webpack-node-externals": "1.7.2"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "10"
          }
        }
      ]
    ]
  },
...
```

I cannot commit with this error in tests.

**Comment by Richienb** [comment]
Webpack isn't transpiling import syntax to require syntax.

**Comment by hp77-creator** [comment]
So how to overcome this error? Why can't I just use 'import'?
