### ISSUE TITLE
Question: Proxy with https protocol not worked

### ISSUE THREAD

**Issue by lugin-design** [node-fetch/node-fetch#892]
```javascript
const HttpsProxyAgent = require('https-proxy-agent')
const fetch = require('node-fetch')

const url = 'https://jsonplaceholder.typicode.com/todos/1'
const proxy = 'https://36.75.245.191:8080'
// const proxy = 'http://36.75.245.191:8080' <= with http worked

const sendReq = async () => {
    try {
        const res = await fetch(url, { agent: new HttpsProxyAgent(proxy) })
        const data = await res.json()
        console.log(data)
    } catch (err) {
        console.log(err)
    }
}

sendReq()
```

> Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established
    at ClientRequest.onError (C:\Projects\...\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}

Same on Python worked

```python
import requests
import json

proxies = {
    'https': 'https://36.75.245.191:8080'
}

resp = requests.get('https://jsonplaceholder.typicode.com/todos/1', proxies=proxies)
print(json.loads(resp.text))
```

**Comment by tekwiz** [comment]
@lugin-design What happens if you try the request with just the https module?  Try this and let me know what happens:

```js
const HttpsProxyAgent = require('https-proxy-agent')
const https = require('https');

const url = 'https://jsonplaceholder.typicode.com/todos/1'
const proxy = 'https://36.75.245.191:8080'
// const proxy = 'http://36.75.245.191:8080' <= with http worked

https.get(url, { agent: new HttpsProxyAgent(proxy) }, res => {
  console.dir(res);
  res.pipe(process.stdout);
}).on('error', e => console.error(e.stack));
```

**Comment by justwink** [comment]
Same issue in CI
