### ISSUE TITLE
Bug: "RangeError: Invalid typed array length: 5242880000" when posting ArrayBuffer with huge size

### ISSUE THREAD

**Issue by jeremymeng** [node-fetch/node-fetch#893]
https://github.com/Azure/azure-sdk-for-js/issues/9481#issuecomment-644488836

**Reproduction**

Posting an `ArrayBuffer` as request.Body with size > `Buffer` max size

**Expected behavior**
It should work as ArrayBuffer does not have this size limit

**Actual**

```
"RangeError: Invalid typed array length: 5242880000
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at fromArrayBuffer (buffer.js:457:10)
    at Function.from (buffer.js:276:14)
    at Request.Body (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\node-fetch\2.6.0\node_modules\node-fetch\lib\index.js:197:17)
    at new Request (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\node-fetch\2.6.0\node_modules\node-fetch\lib\index.js:1198:8)
    at S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\node-fetch\2.6.0\node_modules\node-fetch\lib\index.js:1403:19
    at new Promise (<anonymous>)
    at fetch (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\node-fetch\2.6.0\node_modules\node-fetch\lib\index.js:1401:9)
    at NodeFetchHttpClient.<anonymous> (S:\dev\azure-sdk-for-js\sdk\core\core-http\src\nodeFetchHttpClient.ts:91:12)
    at step (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:140:27)
    at Object.next (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:121:57)
    at S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:110:16)
    at NodeFetchHttpClient.fetch (S:\dev\azure-sdk-for-js\sdk\core\core-http\dist\coreHttp.node.js:2551:22)
    at NodeFetchHttpClient.<anonymous> (S:\dev\azure-sdk-for-js\sdk\core\core-http\src\fetchHttpClient.ts:136:45)
    at step (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:140:27)
    at Object.next (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:121:57)
    at fulfilled (S:\dev\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\tslib\2.0.0\node_modules\tslib\tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
```

A workaround is to convert the ArrayBuffer to Stream.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.0
| node             | v12.16.1
| npm              | 6.13.4
| Operating System | Windows 10

**Additional context**

**Comment by JefferyHus** [comment]
As the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length) states:

```txt
The JavaScript exception "Invalid array length" occurs when creating an Array or an ArrayBuffer which has a length which is either negative or larger or equal to 2^32, or when setting the Array.length property to a value which is either negative or larger or equal to 2^32.
```

And if we do the math of 2^32, it gives us this number `4 294 967 296` and your `ArrayBuffer` size is `5242880000` so it is clearly out of the limit range.

The issue is not related to the library, therefore closing it.

**Comment by jeremymeng** [comment]
You can see from the stack trace that it is fine to create ArrayBuffer with this size. The error is thrown from node-fetch code when fromBuffer is called.

**Comment by JefferyHus** [comment]
Let me give it a try, because I have read documentations about the Buffer and how it can be limited..etc
I will give it a test and get back to you

**Comment by jimmywarting** [comment]
I guess a better container for this would be a Blob, both for posting and receiving huge data. but something that could be a better option would be to just use stream

A blob can contain multiple chunks of smaller buffers.

Now when i think about it... This code isn't a perfect:
https://github.com/node-fetch/node-fetch/blob/1fdc218a64f8bc2c85bec0ca59a85973ef5e1f0a/src/body.js#L100-L111

Think we should rather read all the chunks and not concatenate all of it into one buffer. to avoid such ArrayBuffer size limitation.
We should rather do something like:

```js
 		const chunks = [];
 		for await (let chunk of this.body) {
			chunks.push(chunk);
		}
  
 		return new Blob(chunks, { 
 			type: ct 
 		}); 
```
This will directly reflect onto blob.stream() which emits Uint8arrays later on. And it would be best if that wasn't one single huge buffer

We previously used one single Buffer internally in Blobs to handle slicing before... but now it operates on blob parts instead. and the slice work a bit different now
