### ISSUE TITLE
Bug: crashes on type error (inside catch block)

### ISSUE THREAD

**Issue by LaurentDhont** [node-fetch/node-fetch#954]
When I try to fetch an URL (which I cannot know) inside a try catch block, the application crashes anyway with error:
/node_modules/node-fetch/lib/index.js:676
                throw new TypeError(`${name} is not a legal HTTP header name`);

**Expected behavior**

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 6.2.1
| node             | 12.16.2
| npm              | 6.14.4
| Operating System | Ubuntu 20.04.1 LTS

**Additional context**

Here you can find my code (the code gets root url's from a file):

`const path = require('path');
const fs = require('fs');
const readline = require('readline');
const fetch = require('node-fetch');

const readStream = fs.createReadStream('file', {
    encoding: "utf8"
});

const interFace = readline.createInterface({
    input: readStream
});

interFace.on('line', async (root) => {
        let error = null;
        let html = null;
        let statusCode = null;

            try {
                const response = await fetch('http://' + root);
                statusCode = response.status;
                html = await response.text();
            }
            catch (e) {
                error = e.message;
            }
        }
});

interFace.on('close', (evt) => {
});
`

**Comment by xxczaki** [comment]
Could you please correct the used node-fetch version? `6.2.1` does not exist.

**Comment by LaurentDhont** [comment]
Sorry, I made a type. Its correct now

**Comment by warriordog** [comment]
I can reproduce this on this on the latest version of node-fetch by trying to request any "invalid" URL. Something internal to node-fetch fails to catch an error which bubbles all the way back up to Node, killing the process with an Unhandled Exception shutdown. Here's an example stack trace:

```
Jul 04 13:17:06 campsite run.sh[990173]: ERR    [core]          Uncaught exception (uncaughtException): TypeError: https://blog.strangeobject.space@newstrujew/ is an url with embedded credentials.
Jul 04 13:17:06 campsite run.sh[990173]:     at new Request (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:60:10)
Jul 04 13:17:06 campsite run.sh[990173]:     at ClientRequest.<anonymous> (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:21)
Jul 04 13:17:06 campsite run.sh[990173]:     at ClientRequest.emit (node:events:536:35)
Jul 04 13:17:06 campsite run.sh[990173]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:716:27)
Jul 04 13:17:06 campsite run.sh[990173]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSSocket.socketOnData (node:_http_client:558:22)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSSocket.emit (node:events:536:35)
Jul 04 13:17:06 campsite run.sh[990173]:     at addChunk (node:internal/streams/readable:561:12)
Jul 04 13:17:06 campsite run.sh[990173]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Jul 04 13:17:06 campsite run.sh[990173]:     at Readable.push (node:internal/streams/readable:392:5)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
Jul 04 13:17:06 campsite run.sh[990173]: file:///home/sharkey/sharkey/packages/backend/built/boot/entry.js:60
Jul 04 13:17:06 campsite run.sh[990173]:         throw err;
Jul 04 13:17:06 campsite run.sh[990173]:         ^
Jul 04 13:17:06 campsite run.sh[990173]: TypeError: https://blog.strangeobject.space@newstrujew/ is an url with embedded credentials.
Jul 04 13:17:06 campsite run.sh[990173]:     at new Request (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:60:10)
Jul 04 13:17:06 campsite run.sh[990173]:     at ClientRequest.<anonymous> (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:21)
Jul 04 13:17:06 campsite run.sh[990173]:     at ClientRequest.emit (node:events:536:35)
Jul 04 13:17:06 campsite run.sh[990173]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:716:27)
Jul 04 13:17:06 campsite run.sh[990173]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSSocket.socketOnData (node:_http_client:558:22)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSSocket.emit (node:events:536:35)
Jul 04 13:17:06 campsite run.sh[990173]:     at addChunk (node:internal/streams/readable:561:12)
Jul 04 13:17:06 campsite run.sh[990173]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Jul 04 13:17:06 campsite run.sh[990173]:     at Readable.push (node:internal/streams/readable:392:5)
Jul 04 13:17:06 campsite run.sh[990173]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
Jul 04 13:17:06 campsite run.sh[990173]: Node.js v22.13.1
Jul 04 13:17:06 campsite run.sh[989307]:  ELIFECYCLE  Command failed with exit code 7.
Jul 04 13:17:06 campsite systemd[1]: sharkey.api.service: Main process exited, code=exited, status=7/NOTRUNNING
Jul 04 13:17:06 campsite systemd[1]: sharkey.api.service: Failed with result 'exit-code'.
```

another example:

```
Jul 03 17:45:51 campsite run.sh[2158]: TypeError: https://blog.strangeobject.space@interstellarteahouse/ is an url with embedded credentials.
Jul 03 17:45:51 campsite run.sh[2158]:     at new Request (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:60:10)
Jul 03 17:45:51 campsite run.sh[2158]:     at ClientRequest.<anonymous> (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:21)
Jul 03 17:45:51 campsite run.sh[2158]:     at ClientRequest.emit (node:events:536:35)
Jul 03 17:45:51 campsite run.sh[2158]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:716:27)
Jul 03 17:45:51 campsite run.sh[2158]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
Jul 03 17:45:51 campsite run.sh[2158]:     at TLSSocket.socketOnData (node:_http_client:558:22)
Jul 03 17:45:51 campsite run.sh[2158]:     at TLSSocket.emit (node:events:536:35)
Jul 03 17:45:51 campsite run.sh[2158]:     at addChunk (node:internal/streams/readable:561:12)
Jul 03 17:45:51 campsite run.sh[2158]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Jul 03 17:45:51 campsite run.sh[2158]:     at Readable.push (node:internal/streams/readable:392:5)
Jul 03 17:45:51 campsite run.sh[2158]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
Jul 03 17:45:51 campsite run.sh[2158]: Node.js v22.13.1
```

and another:

```
Jun 30 20:24:05 campsite run.sh[759428]: ERR    [core]          Uncaught exception (uncaughtException): TypeError: https://user.well.com@driscoll/ is an url with embedded credentials.
Jun 30 20:24:05 campsite run.sh[759428]:     at new Request (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:60:10)
Jun 30 20:24:05 campsite run.sh[759428]:     at ClientRequest.<anonymous> (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:21)
Jun 30 20:24:05 campsite run.sh[759428]:     at ClientRequest.emit (node:events:536:35)
Jun 30 20:24:05 campsite run.sh[759428]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:716:27)
Jun 30 20:24:05 campsite run.sh[759428]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSSocket.socketOnData (node:_http_client:558:22)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSSocket.emit (node:events:536:35)
Jun 30 20:24:05 campsite run.sh[759428]:     at addChunk (node:internal/streams/readable:561:12)
Jun 30 20:24:05 campsite run.sh[759428]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Jun 30 20:24:05 campsite run.sh[759428]:     at Readable.push (node:internal/streams/readable:392:5)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
Jun 30 20:24:05 campsite run.sh[759428]: file:///home/sharkey/sharkey/packages/backend/built/boot/entry.js:60
Jun 30 20:24:05 campsite run.sh[759428]:         throw err;
Jun 30 20:24:05 campsite run.sh[759428]:         ^
Jun 30 20:24:05 campsite run.sh[759428]: TypeError: https://user.well.com@driscoll/ is an url with embedded credentials.
Jun 30 20:24:05 campsite run.sh[759428]:     at new Request (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/request.js:60:10)
Jun 30 20:24:05 campsite run.sh[759428]:     at ClientRequest.<anonymous> (file:///home/sharkey/sharkey/node_modules/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js:236:21)
Jun 30 20:24:05 campsite run.sh[759428]:     at ClientRequest.emit (node:events:536:35)
Jun 30 20:24:05 campsite run.sh[759428]:     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:716:27)
Jun 30 20:24:05 campsite run.sh[759428]:     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSSocket.socketOnData (node:_http_client:558:22)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSSocket.emit (node:events:536:35)
Jun 30 20:24:05 campsite run.sh[759428]:     at addChunk (node:internal/streams/readable:561:12)
Jun 30 20:24:05 campsite run.sh[759428]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Jun 30 20:24:05 campsite run.sh[759428]:     at Readable.push (node:internal/streams/readable:392:5)
Jun 30 20:24:05 campsite run.sh[759428]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:189:23)
Jun 30 20:24:05 campsite run.sh[759428]: Node.js v22.13.1
Jun 30 20:24:05 campsite run.sh[759091]:  ELIFECYCLE  Command failed with exit code 7.
Jun 30 20:24:05 campsite systemd[1]: sharkey.api.service: Main process exited, code=exited, status=7/NOTRUNNING
Jun 30 20:24:05 campsite systemd[1]: sharkey.api.service: Failed with result 'exit-code'.
```

As a workaround, you can pre-validate the input URL and/or apply a global error handler like this:

```typescript
process.on('uncaughtException', (err) => {
  // Workaround for https://github.com/node-fetch/node-fetch/issues/954
  if (String(err).match(/^TypeError: .+ is an? url with embedded credentials.$/)) {
    console.debug('Suppressed node-fetch issue#954, but the current job may fail.');
    return;
  }

  // Workaround for https://github.com/node-fetch/node-fetch/issues/1845
  if (String(err) === 'TypeError: Cannot read properties of undefined (reading \'body\')') {
    console.debug('Suppressed node-fetch issue#1845, but the current job may fail.');
    return;
  }

  // Throw all other errors to avoid inconsistent state.
  // (per nodeJS docs, it's unsafe to suppress all errors in an uncaughtException handler.)
  throw err;
});
```

I'm unsure if this is related, but it's worth noting that all of the examples I've seen were caused by a request to a valid URL that *redirected* to an invalid one. Maybe node-fetch doesn't validate the `Location` header before following it?
